export const TeamsData = [
  {
    id: "1",
    name: "John Doe",
    designation: "Software Engineer",
    email: "johndoe@example.com",
    team: "Backend Development",
    status: "active",
    joinedDate: "2023-01-15",
  },
  {
    id: "2",
    name: "Jane Smith",
    designation: "Frontend Developer",
    email: "janesmith@example.com",
    team: "Frontend Development",
    status: "on-leave",
    joinedDate: "2022-11-10",
  },
  {
    id: "3",
    name: "Alice Johnson",
    designation: "UI/UX Designer",
    email: "alicejohnson@example.com",
    team: "Design Team",
    status: "active",
    joinedDate: "2021-07-25",
  },
  {
    id: "4",
    name: "Bob Brown",
    designation: "DevOps Engineer",
    email: "bobbrown@example.com",
    team: "Infrastructure",
    status: "inactive",
    joinedDate: "2020-03-15",
  },
  {
    id: "5",
    name: "Charlie Davis",
    designation: "Product Manager",
    email: "charliedavis@example.com",
    team: "Product Management",
    status: "active",
    joinedDate: "2019-09-05",
  },
];
